sudo: required

services:
  - docker

language: php

php:
  - 5.5

env:
  global:
    - secure: "kM/EpxIyynynJTm2qK/T7CCIooth99Xd1Q3VEwABmX0oK0R0proI0GgklSKFd46zJwZg4CPmrBx9M7AIYHraiHVyVo0XYV3lHYaT0/6fuHMhDk0OuHOwL7VOCrnRULWRS1ItuwtWj6ViybVMz9YeLhpQvU73+8eJVP8aTFy9fVRHGddOmzkPWkycMZlDg9QlEvXpmwbPyTh5LmveeSeUhusOAF1p7+m621fEeX7wJEKBBlZtYAR1yQ6qW0dV0nFhViqxXpUeHNPFs4hH5YMKFCIA+02Rafw9enWxO45fYVQ9VhPQHqBBfmDxr7ELrEN1Vj4HnxiW64fUvnpGuVEvTfyPs1ebzdmdzD34GfbHTfFHMxAMEv4iga58pD5ccpi0EHpgLU20N5uw41un1qyw70/90VkeFJ33FFvSXHLob4k33a51XmgXEYXYBvQBdFnbiRHYyqfUDuGejzaQuxsE+/dentHIUgXBU0vOTcvG34QptIsw2v6YYTdxpNyS5IiJz2kTRHwQFs8iDhHo6nzhIgWLdP83Mgbq6nTQ116eaAdDOgLnNkDeIcJxLdr2jvDxVPpvIOvgvF3qTNLY1sv5BzTutMSnoR5dhby153MyJHLQVORT3TZqyU5kmHTDo6xHHodSgmo9elyPZ/Em0Ixi3A5KZRcxHMtVppT8rQfPL2I=" 
    - secure: "kHq51yGny8fCyBMXeuAr0POJdlOE28UN3Xs5Sf9u4V9FpRLRo83DObR0c1cFePos0W8yoo11zOwX8FjtU11NiYBYEuHafXTWXtiuY4OG6P2eovUYGFo46ppZ/XtaS8f+gYjlSPlmkLV90RsDI6ZFXK4GalMO5TAYVzpahjxdhS5jcS0MrA5O60jo/0zwefqMX6UAwT7uyeB4sGxhtLzi/b1l8n0fl757p9GgZcNE+8rIE4gT09DJijVF5DvUNe/TvlPI21oX+NbaB6RwhYOPe3d0ModEKTbiKt1b6BA7HTfJOQQiu+Z+12ypihymAE+FbVjGxHHaELTd3oiylYjVYqwaPAalrLgHMVU6pKFD/SiQbrs6Xb1WllTvS+RJKxKwnDnVVxSv+GQbiMblsf6hMcUno1N38zjTa1jcGvcWk+HzIwnx9hj+2EsKEtx+AAjSMtQPmYvJgGoxdIExkl5EW4nRP8nxm40AlcrwhYbOOLOocB2EtiRAkqSdxyXowE3LCxuX08q3tiURtYh+VO9iY5H6p89kdPGAMIXmZUCNrYife36yNcAZIMjN3ocViGiyDDgoZgEr8VIi+5hx0r4DpwaTupsO2T0qYOFqQ8DlU8c7YZ/Gt7BW08jNwymlsFyPuPJ5zVEXQSwq03/pv0iavN9azK+2KHyYx/6PsGeBAOY="
    - secure: "HMk3u0PT8yWaIS1RM42yUZoO+7IFeGiFGqq+coVqD3aT9+VDrR+lbGenR/rQHFLihgm6diyxykzx7Rtw86/uCWY+QqE9n8FvtN5Ezrv6kxXklegYFAz56TKyPefvcTmM/E6Fc2yacDEvHPK3Wfec92d07VYQJojLzihYAqRTzZ2btSuwbYWMo+78mUhflVESd2HficD2szPC4vk/r5lAYHzvKwkMYoo3FApDsygbvZ7wYRjnejo/KmdRn5w8kkREkuUOS5qcCTzq0fdEOhrFwqQlMJ7IwvukQbjoYe3fVzfwTEeNpYSx8A2x5TSicd65i1dgBYHLNLeraQOzpeJ93dC0CjWOAiJCjd06WmK/4Z6uBkvGkZxSrbjatpVMN1kN84L7cgFggXhjRUumrzmG7xUbFW6yBacx1c8ExcVawgsgr2HoQBET2iKFUx0Yw/lG1nyNqJl6SNDCQHxX2ArARwkip67XqljWR6zbXa/CA+EGWnib+Y7sm/EZ9u0lIIcGceuiAWmc0Pvv1sJTgxg9IyqakQYHlGIx16Ri/3m2VvOSPMpKoihiHDkk3UCjbh15kwTTfspOcZrw0mjsfAKCDqKO3r0BnxDgEbh1uKFIUMw2YiSmkxeE33+fLfjfGvAxjiUhlX7wr1QUD9qZoz1EKac7LDR+zSgLNnf0wbUsfaQ="
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=imshashank/aws-sdk-php
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "php-5.6"; else echo php-5.6-$TRAVIS_BRANCH ; fi`
  - docker build -f php-5.6/Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO:$TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "php-7.0"; else echo php-7.0-$TRAVIS_BRANCH ; fi`
  - docker build -f php-7.0/Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO:$TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "xdebug"; else echo xdebug-$TRAVIS_BRANCH ; fi`
  - docker build -f xdebug/Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO:$TAG
